APP_NAME=畅美科技
APP_ENV=local
APP_KEY=base64:ssFKDfL4a7Hh9iOkx4VDMjtiYwS50iTw4t32btlzdqc=
APP_DEBUG=true
APP_LOG_LEVEL=dev
APP_LOG=daily
APP_URL=http://xfjb.api.dev.com/

DB_CONNECTION=mysql
DB_HOST=192.168.0.13
DB_PORT=3306
DB_DATABASE=yicms
DB_USERNAME=root
DB_PASSWORD=abc123

BROADCAST_DRIVER=log
CACHE_DRIVER=redis
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

REDIS_HOST=192.168.0.13
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.mailtrap.io
MAIL_PORT=2525
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=

GEETEST_ID= 你的极致验证码id
GEETEST_KEY=你的极致验证码key

ROOT_DOMAIN=dev.com